setono_sylius_catalog_promotion_admin_catalog_promotion_update:
    resource: |
        alias: setono_sylius_catalog_promotion.catalog_promotion_update
        section: admin
        templates: '@SyliusAdmin\\Crud'
        grid: setono_sylius_catalog_promotion_admin_catalog_promotion_update
        permission: true
        vars:
            index:
                icon: in cart
    type: sylius.resource

setono_sylius_catalog_promotion_admin_catalog_promotion:
    resource: |
        alias: setono_sylius_catalog_promotion.catalog_promotion
        section: admin
        templates: '@SyliusAdmin\\Crud'
        except: ['show']
        redirect: update
        grid: setono_sylius_catalog_promotion_admin_catalog_promotion
        permission: true
        vars:
            all:
                subheader: setono_sylius_catalog_promotion.ui.manage_catalog_promotions
                templates:
                    form: "@SetonoSyliusCatalogPromotionPlugin/admin/catalog_promotion/_form.html.twig"
            index:
                icon: in cart
            update:
                templates:
                    form: "@SetonoSyliusCatalogPromotionPlugin/admin/catalog_promotion/_form.html.twig"
    type: sylius.resource

setono_sylius_consent_management_admin_update_all_catalog:
    path: /catalog-promotions/update-all
    methods: GET
    defaults:
        _controller: Setono\SyliusCatalogPromotionPlugin\Controller\UpdateAllAction
